---
title: "R Notebook"
output: html_notebook
---

```{r}
end_season_summary <- get_season_team_stats(
  country = "ENG", 
  gender = "M", 
  season_end_year = c(2018:2022), 
  tier = "1st",
  stat_type = "league_table")

saveRDS(end_season_summary, "season_summary.rds")

end_season_summary <- read_rds("data/season_summary.rds")
```

```{r}
shooting_season_summary <- get_season_team_stats(
  country = "ENG", 
  gender = "M", 
  season_end_year = c(2018:2022), 
  tier = "1st",
  stat_type = "shooting")

saveRDS(end_season_summary, "data/shooting_season_summary.rds")

shooting_season_summary
```

```{r}
passing_season_summary <- get_season_team_stats(
  country = "ENG", 
  gender = "M", 
  season_end_year = c(2018:2022), 
  tier = "1st",
  stat_type = "passing")

saveRDS(end_season_summary, "data/passing_season_summary.rds")

passing_season_summary
```

```{r}
passing_types_season_summary <- get_season_team_stats(
  country = "ENG", 
  gender = "M", 
  season_end_year = c(2018:2022), 
  tier = "1st",
  stat_type = "passing_types")

saveRDS(end_season_summary, "data/passing_types_season_summary.rds")

passing_types_season_summary
```

```{r}
goal_shot_creation_summary <- get_season_team_stats(
  country = "ENG", 
  gender = "M", 
  season_end_year = c(2018:2022), 
  tier = "1st",
  stat_type = "goal_shot_creation")

saveRDS(end_season_summary, "data/goal_shot_creation_summary.rds")

goal_shot_creation_summary
```

```{r}
misc_season_summary <- get_season_team_stats(
  country = "ENG", 
  gender = "M", 
  season_end_year = c(2018:2022), 
  tier = "1st",
  stat_type = "misc")

saveRDS(end_season_summary, "data/misc_season_summary.rds")

misc_season_summary
```

